apiVersion: 1
datasources:
  - name: Tempo
    uid: autostrada-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
  - name: Loki
    uid: autostrada-loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: 'trace_id=([a-f0-9]{32})'
          datasourceUid: autostrada-tempo
          url: '${__value.raw}'
  - name: Prometheus
    uid: autostrada-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
