#!/bin/sh
# The official MySQL image sources non-executable init scripts. Keep strict
# options and the E2E early exit inside a subshell, never in its entrypoint.
(
set -eu

if [ "${AUTOSTRADA_E2E:-false}" = "true" ]; then
	exit 0
fi

mysql --protocol=socket -uroot -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE" <<SQL
CREATE DATABASE IF NOT EXISTS \`$IDENTITY_DB_NAME\`;
CREATE USER IF NOT EXISTS '$DB_RUNTIME_USERNAME'@'%' IDENTIFIED BY '$DB_RUNTIME_PASSWORD';
CREATE USER IF NOT EXISTS '$DB_MIGRATION_USERNAME'@'%' IDENTIFIED BY '$DB_MIGRATION_PASSWORD';
CREATE USER IF NOT EXISTS '$IDENTITY_DB_USERNAME'@'%' IDENTIFIED BY '$IDENTITY_DB_PASSWORD';
GRANT ALL PRIVILEGES ON \`$MYSQL_DATABASE\`.* TO '$DB_RUNTIME_USERNAME'@'%';
GRANT ALL PRIVILEGES ON \`$MYSQL_DATABASE\`.* TO '$DB_MIGRATION_USERNAME'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON \`$IDENTITY_DB_NAME\`.* TO '$IDENTITY_DB_USERNAME'@'%';
CREATE DATABASE IF NOT EXISTS \`$NOTIFICATION_DB_NAME\`;
CREATE USER IF NOT EXISTS '$NOTIFICATION_DB_USERNAME'@'%' IDENTIFIED BY '$NOTIFICATION_DB_PASSWORD';
GRANT ALL PRIVILEGES ON \`$NOTIFICATION_DB_NAME\`.* TO '$NOTIFICATION_DB_USERNAME'@'%';
CREATE DATABASE IF NOT EXISTS \`$PAYMENT_DB_NAME\`;
CREATE USER IF NOT EXISTS '$PAYMENT_DB_USERNAME'@'%' IDENTIFIED BY '$PAYMENT_DB_PASSWORD';
GRANT ALL PRIVILEGES ON \`$PAYMENT_DB_NAME\`.* TO '$PAYMENT_DB_USERNAME'@'%';
FLUSH PRIVILEGES;
SQL
)
