#!/bin/sh
set -eu

mysql --protocol=socket -uroot -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE" <<SQL
CREATE DATABASE IF NOT EXISTS \`$IDENTITY_DB_NAME\`;
CREATE USER IF NOT EXISTS '$DB_RUNTIME_USERNAME'@'%' IDENTIFIED BY '$DB_RUNTIME_PASSWORD';
CREATE USER IF NOT EXISTS '$DB_MIGRATION_USERNAME'@'%' IDENTIFIED BY '$DB_MIGRATION_PASSWORD';
CREATE USER IF NOT EXISTS '$IDENTITY_DB_USERNAME'@'%' IDENTIFIED BY '$IDENTITY_DB_PASSWORD';
GRANT ALL PRIVILEGES ON \`$MYSQL_DATABASE\`.* TO '$DB_RUNTIME_USERNAME'@'%';
GRANT ALL PRIVILEGES ON \`$MYSQL_DATABASE\`.* TO '$DB_MIGRATION_USERNAME'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON \`$IDENTITY_DB_NAME\`.* TO '$IDENTITY_DB_USERNAME'@'%';
FLUSH PRIVILEGES;
SQL
