import { createBrowserRouter } from 'react-router-dom';

import AppLayout from './components/layout/AppLayout.jsx';
import AuctionsPage from './pages/AuctionsPage.jsx';
import ListingsPage from './pages/ListingsPage.jsx';
import {
  AdminCarsPage,
  AdminOrdersPage,
  AdminPartFormPage,
  AdminStorePartsPage,
  AdminTransactionsPage,
  AdminUsersPage,
  AppointmentsPage,
  AuctionDetailPage,
  AuctionFormPage,
  BidsPage,
  CartPage,
  CheckoutSuccessPage,
  DepositsPage,
  ForgotPasswordPage,
  HomePage,
  ListingDetailPage,
  ListingFormPage,
  LoginPage,
  NotificationsPage,
  OrderDetailPage,
  OrdersPage,
  PartDetailPage,
  ProfileEditPage,
  ProfilePage,
  PublicProfilePage,
  RegisterPage,
  ResetPasswordPage,
  StaticContentPage,
  ThankYouPage,
  UserAuctionsPage,
  UserListingsPage,
  WatchlistPage,
} from './pages/MigratedPages.jsx';
import NotFoundPage from './pages/NotFoundPage.jsx';
import StorePage from './pages/StorePage.jsx';

export const routes = [
  {
    path: '/',
    element: <AppLayout />,
    children: [
      { index: true, element: <HomePage /> },
      { path: 'login', element: <LoginPage /> },
      { path: 'register', element: <RegisterPage /> },
      { path: 'register/account', element: <RegisterPage /> },
      { path: 'register/profile', element: <RegisterPage /> },
      { path: 'register/thank-you', element: <ThankYouPage /> },
      { path: 'forgot-password', element: <ForgotPasswordPage /> },
      { path: 'reset-password', element: <ResetPasswordPage /> },
      { path: 'about-us', element: <StaticContentPage page="about-us" /> },
      { path: 'contact-us', element: <StaticContentPage page="contact-us" /> },
      { path: 'auctions', element: <AuctionsPage /> },
      { path: 'cars', element: <AuctionsPage /> },
      { path: 'live-auctions', element: <AuctionsPage /> },
      { path: 'browse-auctions', element: <AuctionsPage /> },
      { path: 'auction-listings', element: <AuctionsPage /> },
      { path: 'auctions/:id', element: <AuctionDetailPage /> },
      { path: 'auction/:id', element: <AuctionDetailPage /> },
      { path: 'cars/:make/:model/:year/:id', element: <AuctionDetailPage /> },
      { path: 'listings', element: <ListingsPage /> },
      { path: 'car-listings', element: <ListingsPage /> },
      { path: 'cars-for-sale', element: <ListingsPage /> },
      { path: 'vehicle-listings', element: <ListingsPage /> },
      { path: 'listings/:id', element: <ListingDetailPage /> },
      { path: 'car-listings/:id', element: <ListingDetailPage /> },
      { path: 'cars-for-sale/:id', element: <ListingDetailPage /> },
      { path: 'parts', element: <StorePage /> },
      { path: 'store', element: <StorePage /> },
      { path: 'store/parts', element: <StorePage /> },
      { path: 'car-parts', element: <StorePage /> },
      { path: 'parts-store', element: <StorePage /> },
      { path: 'parts/:id', element: <PartDetailPage /> },
      { path: 'store/parts/:id', element: <PartDetailPage /> },
      { path: 'car-parts/:id', element: <PartDetailPage /> },
      { path: 'cart', element: <CartPage /> },
      { path: 'orders', element: <OrdersPage /> },
      { path: 'orders/:id', element: <OrderDetailPage /> },
      { path: 'store/checkout/success', element: <CheckoutSuccessPage /> },
      { path: 'listing-deposits/success', element: <CheckoutSuccessPage deposit /> },
      { path: 'view-user/:firstName/:idProfile', element: <PublicProfilePage /> },
      { path: 'profiles/:idProfile', element: <PublicProfilePage /> },
      { path: 'user', element: <ProfilePage /> },
      { path: 'user/my-profile', element: <ProfilePage /> },
      { path: 'user/profile', element: <ProfilePage /> },
      { path: 'user/edit-profile', element: <ProfileEditPage /> },
      { path: 'user/profile/edit', element: <ProfileEditPage /> },
      { path: 'user/upload-picture', element: <ProfilePage /> },
      { path: 'user/my-posted-car', element: <UserAuctionsPage /> },
      { path: 'user/my-posted-cars', element: <UserAuctionsPage /> },
      { path: 'user/my-auctions', element: <UserAuctionsPage /> },
      { path: 'user/auctions', element: <UserAuctionsPage /> },
      { path: 'user/post-car', element: <AuctionFormPage /> },
      { path: 'user/auctions/new', element: <AuctionFormPage /> },
      { path: 'user/edit-posted-car', element: <AuctionFormPage /> },
      { path: 'user/auctions/:id/edit', element: <AuctionFormPage /> },
      { path: 'user/listings', element: <UserListingsPage /> },
      { path: 'user/my-listings', element: <UserListingsPage /> },
      { path: 'user/car-listings', element: <UserListingsPage /> },
      { path: 'user/listings/new', element: <ListingFormPage /> },
      { path: 'user/listings/:id/edit', element: <ListingFormPage /> },
      { path: 'user/followed-auctions', element: <WatchlistPage /> },
      { path: 'user/favorites', element: <WatchlistPage /> },
      { path: 'user/watchlist', element: <WatchlistPage /> },
      { path: 'user/notifications', element: <NotificationsPage /> },
      { path: 'user/test-drive', element: <AppointmentsPage /> },
      { path: 'user/test-rides', element: <AppointmentsPage /> },
      { path: 'user/appointments', element: <AppointmentsPage /> },
      { path: 'user/bids', element: <BidsPage /> },
      { path: 'car-bid', element: <AuctionDetailPage /> },
      { path: 'test-drive/:id', element: <AuctionDetailPage /> },
      { path: 'user/listing-deposits', element: <DepositsPage /> },
      { path: 'user/deposits', element: <DepositsPage /> },
      { path: 'admin', element: <AdminUsersPage /> },
      { path: 'admin/dashboard', element: <AdminUsersPage /> },
      { path: 'admin/users', element: <AdminUsersPage /> },
      { path: 'admin/car-management', element: <AdminCarsPage /> },
      { path: 'admin/cars', element: <AdminCarsPage /> },
      { path: 'admin/auctions', element: <AdminCarsPage /> },
      { path: 'admin/listings', element: <AdminCarsPage /> },
      { path: 'admin/transactions', element: <AdminTransactionsPage /> },
      { path: 'admin/store/parts', element: <AdminStorePartsPage /> },
      { path: 'admin/store', element: <AdminStorePartsPage /> },
      { path: 'admin/parts', element: <AdminStorePartsPage /> },
      { path: 'admin/store/parts/new', element: <AdminPartFormPage /> },
      { path: 'admin/store/parts/:id/edit', element: <AdminPartFormPage /> },
      { path: 'admin/store/orders', element: <AdminOrdersPage /> },
      { path: 'admin/orders', element: <AdminOrdersPage /> },
      { path: 'admin/store/orders/:id', element: <OrderDetailPage admin /> },
      { path: '*', element: <NotFoundPage /> },
    ],
  },
];

export function createAppRouter() {
  return createBrowserRouter(routes);
}
